// docker-compose.yml
version: '3.8'
services:
  backend:
    build: ./backend
    container_name: whaticket-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env.example
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    container_name: whaticket-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.example
    volumes:
      - ./frontend:/app

  db:
    image: postgres:15
    container_name: whaticket-db
    restart: always
    environment:
      POSTGRES_DB: whaticket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: whaticket-redis
    ports:
      - "6379:6379"

volumes:
  pgdata: